package com.KSDT.commands.enums;

public enum CommandType {
//    TODO List all commands in ALLCAPS
    CREATETEAM,
    CREATEPERSON,
    CREATEBOARDINTEAM,
    ADDPERSON,
    CREATEBUGINBOARD,
    CREATESTORYINBOARD,
    CREATEFEEDBACKINBOARD,
    CHANGESTATUS,
    ADDCOMMENT,
    CHANGEBUGPRIORITY;
}
