package com.KSDT.commands.enums;

public enum CommandType {
//    TODO List all commands in ALLCAPS
    CREATETEAM,
    CREATEPERSON,
    CREATEBOARDINTEAM,
    ADDPERSON,
    CREATEWORKITEMINBOARD,
    CHANGESTATUS,
    ADDCOMMENT,
    CHANGEBUGPRIORITY,
    CHANGEBUGSEVERITY,
    CHANGESTORYSIZE,
    CHANGEFEEDBACKRATING,
    CHANGEPRIORITY,
    SHOWALLPEOPLE,
    SHOWALLTEAMS,
    SHOWALLTEAMMEMBERS;
}
