package com.KSDT.commands.enums;

public enum CommandType {
    CREATETEAM,
    CREATEPERSON,
    CREATEBOARDINTEAM,
    ADDPERSON,
    CREATEFEEDBACKINBOARD,
    CREATEBUGINBOARD,
    CREATESTORYINBOARD,
    CHANGESTATUS,
    ADDCOMMENT,
    CHANGEBUGSEVERITY,
    CHANGESTORYSIZE,
    CHANGEFEEDBACKRATING,
    CHANGEPRIORITY,
    SHOWALLPEOPLE,
    SHOWALLTEAMS,
    SHOWALLTEAMMEMBERS,
    SHOWALLTEAMBOARDS,
    SHOWPERSONACTIVITY,
    SHOWTEAMACTIVITY,
    SHOWBOARDACTIVITY,
    ASSIGNWORKITEM,
    UNASSIGNWORKITEM,
    LISTALLWORKITEMS,
    LISTFILTER
}
