package com.KSDT.commands.enums;

public enum CommandType {
//    TODO List all commands in ALLCAPS
    CREATETEAM,
    CREATEPERSON,
    CREATEBOARDINTEAM,
    ADDPERSON,
    CREATEFEEDBACKINBOARD,
    CREATEBUGINBOARD,
    CREATESTORYINBOARD,
    CHANGESTATUS,
    ADDCOMMENT,
    CHANGEBUGPRIORITY,
    CHANGEBUGSEVERITY,
    CHANGESTORYSIZE,
    CHANGEFEEDBACKRATING,
    CHANGEPRIORITY,
    SHOWALLPEOPLE,
    SHOWALLTEAMS,
    SHOWALLTEAMMEMBERS,
    SHOWALLTEAMBOARDS,
    SHOWPERSONACTIVITY,
    SHOWTEAMACTIVITY,
    SHOWBOARDACTIVITY,
    ASSIGNWORKITEM,
    UNASSIGNWORKITEM,
    LISTALLWORKITEMS,
    LISTFILTER
}
